global_costmap:
  update_frequency: 1.5
  publish_frequency: 0.5
  transform_tolerance: 0.5
  width: 10
  height: 10
  origin_x: 0
  origin_y: 0
  static_map: false
  rolling_window: true
  inflation_radius: 0.3
  resolution: 0.01
