local_costmap:
  update_frequency: 2.5
  publish_frequency: 0.5
  transform_tolerance: 0.25
  static_map: false
  rolling_window: true
  width: 5
  height: 5
  origin_x: 0
  origin_y: 0
  resolution: 0.01
  inflation_radius: 0.1
